DISKLOCATIONDATA equ 6

FAT_DIR_NAME equ 0
FAT_DIR_ATTR equ 11
FAT_DIR_NTRES equ 12
FAT_DIR_CREATE_TIME_TENTH equ 13
FAT_DIR_CREATE_TIME equ 14
FAT_DIR_CREATE_DATE equ 16
FAT_DIR_LAST_ACCESS_DATE equ 18
FAT_DIR_FIRST_CLUSTER_HI equ 20
FAT_DIR_LAST_EDIT_TIME equ 22
FAT_DIR_LAST_EDIT_DATE equ 24
FAT_DIR_FIRST_CLUSTER_LOW equ 26
FAT_DIR_FILE_SIZE equ 28
FAT_DIR_DATASIZE equ 32

ATTR_READ_ONLY equ 0x01
ATTR_HIDDEN equ 0x02
ATTR_SYSTEM equ 0x04
ATTR_VOLUME_ID equ 0x08
ATTR_DIRECTORY equ 0x10
ATTR_ARCHIVE equ 0x20


    org A000h
DISKSECTORA:
    
    org A200h
DISKSECTORB:

    org A400h
HDD_DISKA:
    org $+DISKLOCATIONDATA
HDD_DISKB:
    org $+DISKLOCATIONDATA
HDD_DISKC:
    org $+DISKLOCATIONDATA
HDD_DISKD:
    org $+DISKLOCATIONDATA
HDD_DISKE:
    org $+DISKLOCATIONDATA
HDD_DISKF:
    org $+DISKLOCATIONDATA
HDD_DISKG:
    org $+DISKLOCATIONDATA
HDD_DISKH:
    org $+DISKLOCATIONDATA
HDD_DISKI:
    org $+DISKLOCATIONDATA
HDD_DISKJ:
    org $+DISKLOCATIONDATA
HDD_DISKK:
    org $+DISKLOCATIONDATA
HDD_DISKL:
    org $+DISKLOCATIONDATA
HDD_DISKM:
    org $+DISKLOCATIONDATA
HDD_DISKN:
    org $+DISKLOCATIONDATA
HDD_DISKO:
    org $+DISKLOCATIONDATA
HDD_DISKP:
    org $+DISKLOCATIONDATA
HDD_DISKQ:
    org $+DISKLOCATIONDATA
HDD_DISKR:
    org $+DISKLOCATIONDATA
HDD_DISKS:
    org $+DISKLOCATIONDATA
HDD_DISKT:
    org $+DISKLOCATIONDATA
HDD_DISKU:
    org $+DISKLOCATIONDATA
HDD_DISKV:
    org $+DISKLOCATIONDATA
HDD_DISKW:
    org $+DISKLOCATIONDATA
HDD_DISKX:
    org $+DISKLOCATIONDATA
HDD_DISKY:
    org $+DISKLOCATIONDATA
HDD_DISKZ:
    org $+DISKLOCATIONDATA

HDD_CURRENT_LOCATION:
    org $+DISKLOCATIONDATA
HDD_TEMP_LOCATION:
    org $+DISKLOCATIONDATA
HDD_FOLDER_LOCATION:
    org $+DISKLOCATIONDATA
HDD_ROOT_FOLDER:
    org $+DISKLOCATIONDATA
HDD_CURRENT_DRIVE:
    org $+1
HDD_SECTORS_PER_CLUSTER:
    org $+1
HDD_TEMP_CLUSTER:
    org $+4



    org DISKSECTORA+0Dh
FAT_SECTORS_PER_CLUSTER:
    org DISKSECTORA+0Eh
FAT_RESERVED_SECTORS:
    org DISKSECTORA+10h
FAT_NUM_FAT:
    org DISKSECTORA+24h
FAT16_FAT_SECTOR_SIZE_:
FAT32_FAT_SECTOR_SIZE_:






HDD_COUNT:
    org A301h
HDD_CURRENT_HDD:
    org A302h
HDD_CURRENT_ID:
    org A303h
HDD_CURRENT_OFFSET:
    org A304h
HDD_FOLDER0:
    org A308h
HDD_FOLDER1:
    org A30Bh
HDD_FOLDER2:
    org A310h
HDD_FOLDER3:
    org A314h
HDD_FOLDER4:
    org A318h
HDD_FOLDER5:
    org A31Bh
HDD_FOLDER6:
    org A320h
HDD_FOLDER7:
    org A324h
HDD_FOLDER8:
    org A328h
HDD_FOLDER9:
    org A32Bh
HDD_FOLDERA:
    org A330h
HDD_FOLDERB:
    org A334h
HDD_FOLDERC:
    org A338h
HDD_FOLDERD:
    org A33Bh
HDD_FOLDERE:
    org A340h
HDD_FOLDERF:
    org A344h
    org A3ABh
    org A3B0h
HDD_TYPE:
    org A3D0h
HDD_PATH: