DISKLOCATIONDATA equ 6

    org A400h
HDD_DISKA:
    org HDD_DISKA+DISKLOCATIONDATA
HDD_DISKB:
    org HDD_DISKB+DISKLOCATIONDATA
HDD_DISKC:
    org HDD_DISKC+DISKLOCATIONDATA
HDD_DISKD:
    org HDD_DISKD+DISKLOCATIONDATA
HDD_DISKE:
    org HDD_DISKE+DISKLOCATIONDATA
HDD_DISKF:
    org HDD_DISKF+DISKLOCATIONDATA
HDD_DISKG:
    org HDD_DISKG+DISKLOCATIONDATA
HDD_DISKH:
    org HDD_DISKH+DISKLOCATIONDATA
HDD_DISKI:
    org HDD_DISKI+DISKLOCATIONDATA
HDD_DISKJ:
    org HDD_DISKJ+DISKLOCATIONDATA
HDD_DISKK:
    org HDD_DISKK+DISKLOCATIONDATA
HDD_DISKL:
    org HDD_DISKL+DISKLOCATIONDATA
HDD_DISKM:
    org HDD_DISKM+DISKLOCATIONDATA
HDD_DISKN:
    org HDD_DISKN+DISKLOCATIONDATA
HDD_DISKO:
    org HDD_DISKO+DISKLOCATIONDATA
HDD_DISKP:
    org HDD_DISKP+DISKLOCATIONDATA
HDD_DISKQ:
    org HDD_DISKQ+DISKLOCATIONDATA
HDD_DISKR:
    org HDD_DISKR+DISKLOCATIONDATA
HDD_DISKS:
    org HDD_DISKS+DISKLOCATIONDATA
HDD_DISKT:
    org HDD_DISKT+DISKLOCATIONDATA
HDD_DISKU:
    org HDD_DISKU+DISKLOCATIONDATA
HDD_DISKV:
    org HDD_DISKV+DISKLOCATIONDATA
HDD_DISKW:
    org HDD_DISKW+DISKLOCATIONDATA
HDD_DISKX:
    org HDD_DISKX+DISKLOCATIONDATA
HDD_DISKY:
    org HDD_DISKY+DISKLOCATIONDATA
HDD_DISKZ:
    org HDD_DISKZ+DISKLOCATIONDATA





HDD_COUNT:
    org A301h
HDD_CURRENT_HDD:
    org A302h
HDD_CURRENT_ID:
    org A303h
HDD_CURRENT_OFFSET:
    org A304h
HDD_FOLDER0:
    org A308h
HDD_FOLDER1:
    org A30Bh
HDD_FOLDER2:
    org A310h
HDD_FOLDER3:
    org A314h
HDD_FOLDER4:
    org A318h
HDD_FOLDER5:
    org A31Bh
HDD_FOLDER6:
    org A320h
HDD_FOLDER7:
    org A324h
HDD_FOLDER8:
    org A328h
HDD_FOLDER9:
    org A32Bh
HDD_FOLDERA:
    org A330h
HDD_FOLDERB:
    org A334h
HDD_FOLDERC:
    org A338h
HDD_FOLDERD:
    org A33Bh
HDD_FOLDERE:
    org A340h
HDD_FOLDERF:
    org A344h
    org A3ABh
    org A3B0h
HDD_TYPE:
    org A3D0h
HDD_PATH: